name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        dotnet-version: [ '5.0.x', '6.0.x' ]
        
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Use .NET 5 SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
          dotnet-version: '5.0.x'
    - name: Use .NET 6 SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
          dotnet-version: '6.0.x'
    - name: dotnet tool restore
      run: |
          dotnet tool restore
    - name: Test
      run: dotnet test 
